### ISSUE TITLE
requirements.txt or environment.yml

### ISSUE THREAD

**Issue by jordan-schneider** [cagatayyildiz/ODE2VAE#2]
Could I get some form of documentation of what the dependencies are here (including versions)?

https://pip.pypa.io/en/stable/reference/pip_freeze/ or https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#sharing-an-environment would be nice.

**Comment by jordan-schneider** [comment]
For the next person
```
python==3.7
tensorflow==1.15 # or tensorflow-gpu==1.15
matplotlib
scipy
hickle==3.4
torch
tensorflow_probability
torchdiffeq
```

**Comment by jordan-schneider** [comment]
It looks like maybe you need an older version of hickle, as I can't open any data due to `AttributeError: HDF5-file attribute 'CLASS' does not have value 'hickle'!`. I'm investigating. Did you use python 2 for this?

**Comment by jordan-schneider** [comment]
Ah, sorry I see that "The code is developed and tested on `python3.7` and `TensorFlow 1.13`" from the README. I'm now very confused why hickle isn't behaving.

**Comment by jordan-schneider** [comment]
Yeah, hickle 4.1 was the problem. Downgrading to 3.4.0 fixes the problem.

**Comment by cagatayyildiz** [comment]
I believe the problem is solved?

**Comment by jordan-schneider** [comment]
I would really appreciate the specific versions of everything used. I keep having weird problems where I can't write and read from the same hickle version. I also discovered e.g. that tensorflow-probability needs to be before version 0.9.

**Comment by cagatayyildiz** [comment]
My disk is wiped out, so I'm not super sure about the versions. I guess `tensorflow_probability=0.6` and `hickle=3.4.1` will do it. You could also refer to the torch code if you're not trying to replicate the results, it's far more readable.
