### ISSUE TITLE
Velocity encoder in the torch example

### ISSUE THREAD

**Issue by qu-gg** [cagatayyildiz/ODE2VAE#4]
Hello! I have a quick question regarding the minimal PyTorch implementation.
Is the velocity encoder for v0 implemented the same way in this version?

I see the general encoder, but it appears to only take in one image slice and be shared for the velocity and position with its shape of [N, 2q].

Thanks!

**Comment by cagatayyildiz** [comment]
Hi Ryan! In the simple torch implementation, the encoder only takes the initial frames while in general multiple (stacked) frames should be given as input. This is because initial velocity is constant, so no need for multiple frames to extract it.

Cagatay.

**Comment by qu-gg** [comment]
Ah that makes sense with respect to the training set there. Thank you for the reply!
