### ISSUE TITLE
How to plot the walking sequences like in your Readme?

### ISSUE THREAD

**Issue by abdulfatir** [cagatayyildiz/ODE2VAE#5]
Thanks for releasing your code. 

May I know how I can plot CMU Mocap sequences like the animation in your Readme file?

**Comment by cagatayyildiz** [comment]
Hi, did you follow the exactly same preprocessing steps as described in the reference paper?

**Comment by abdulfatir** [comment]
I am using the preprocessed sequences that you released on One Drive. I was wondering if there's a plotting script somewhere or an interpretation of what the 50 dimensions represent? Sorry, if I missed something obvious that exists in your repo.

**Comment by cagatayyildiz** [comment]
I followed the preprocessing steps as in GPDM paper (see the code here http://www.dgp.toronto.edu/~jmwang/gpdm/). You need to revert the preprocessing steps before visualization. Unfortunately I'm not able to find the scripts I used for visualization.
